### ISSUE TITLE
No implimentation for 'j2Intob2World()' method in c++ ! only declaration

### ISSUE THREAD

**Issue by dhiahassen** [iforce2d/b2dJson#11]

**Comment by iforce2d** [comment]
That function should have been removed from the header earlier, sorry. I removed it now.

This function will load a JSON value into an existing world, to 'merge' the two together:
b2World* j2b2World(Json::Value &worldValue, b2World* world = NULL);

More commonly though, you would use this one:
b2World* readFromFile(const char* filename, std::string& errorMsg, b2World* existingWorld = NULL);

**Comment by iforce2d** [comment]
See also the discussion of this in the main docs:
http://www.iforce2d.net/b2djson/#merging
